language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN="8dfcea03-3f4f-4d89-9ac5-d32ea63ad203"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -nxnbatgo@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always